apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: github-release-notification
data:
  PORT: "8080"
  GRPC_PORT: "50051"
  NATS_URL: "nats://nats:4222"
  GRPC_TLS_CA_CERT: "/certs/ca.crt"
  GRPC_TLS_CERT: "/certs/auth.crt"
  GRPC_TLS_KEY: "/certs/auth.key"
  JWT_PRIVATE_KEY: "/certs/jwt-signing.key"
