apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: github-release-notification
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:CHANGE_ME@postgres-auth-db:5432/auth?sslmode=disable"
  ca.crt: |
    <paste contents of certs/ca.crt>
  auth.crt: |
    <paste contents of certs/auth.crt>
  auth.key: |
    <paste contents of certs/auth.key>
  jwt-signing.key: |
    <paste contents of certs/jwt-signing.key>
