syntax = "proto3";

package subscription.v1;

option go_package = "GithubReleaseNotificationAPI/services/subscription/api/gen/subscriptionv1/subscription/v1";

service SubscriptionService {
  rpc Subscribe(SubscribeRequest) returns (SubscribeResponse);
  rpc Confirm(ConfirmRequest) returns (ConfirmResponse);
  rpc Unsubscribe(UnsubscribeRequest) returns (UnsubscribeResponse);
  rpc ListSubscriptions(ListSubscriptionsRequest) returns (ListSubscriptionsResponse);
  rpc ListTrackedRepos(ListTrackedReposRequest) returns (ListTrackedReposResponse);
}

message SubscribeRequest {
  string email = 1;
  string repo  = 2;
}

message SubscribeResponse {
  string message = 1;
}

message ConfirmRequest {
  string token = 1;
}

message ConfirmResponse {
  string message = 1;
}

message UnsubscribeRequest {
  string token = 1;
}

message UnsubscribeResponse {
  string message = 1;
}

message ListSubscriptionsRequest {
  string email = 1;
}

message ListSubscriptionsResponse {
  repeated Subscription subscriptions = 1;
}

message Subscription {
  string email         = 1;
  string repo          = 2;
  bool   confirmed     = 3;
  string last_seen_tag = 4;
}

message ListTrackedReposRequest {}

message ListTrackedReposResponse {
  repeated TrackedRepo repos = 1;
}

message TrackedRepo {
  int64  repo_id   = 1;
  string full_name = 2;
}
