apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  labels:
    app.kubernetes.io/name: postgres-db
    app.kubernetes.io/part-of: github-release-notification
data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "github_release_notifications"
